# Generated by Django 5.0.3 on 2024-03-26 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_portfolio_projecturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='rateSkill_1to100',
        ),
        migrations.AddField(
            model_name='skills',
            name='skills',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
