# Generated by Django 5.0.3 on 2024-03-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_skills_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='title',
        ),
    ]
